# Vigil — build + package + sign
#
# Two intents:
#   make app                       — ad-hoc signed local build for dev/testing
#   make release VERSION=X.Y.Z     — Developer-ID signed, hardened-runtime,
#                                    ready-for-notarization bundle

.PHONY: build icon app release install uninstall status on off doctor verify clean \
        _generate_version _assemble _inject_version _inject_sparkle _trim_sparkle _sign_dev _sign_release

# ---- Configuration ----------------------------------------------------------

APP_NAME           := Vigil
BUNDLE_ID          := com.vigil.app
PREFIX             ?= /usr/local

# Version source of truth: caller-injected. Defaults are a recognisable dev marker.
VERSION            ?= 0.0.0-dev
BUILD              ?= 1

# Codesigning. Ad-hoc by default; release passes the Developer ID identity.
CODESIGN_IDENTITY  ?= -

# Sparkle (both must be set for the updater to activate at runtime —
# see Sources/VigilMenuBar/main.swift configurationIsPresent).
SPARKLE_FEED_URL       ?=
SPARKLE_PUBLIC_ED_KEY  ?=

# Build artefacts
BUILD_DIR          := .build/release
CLI_BIN            := $(BUILD_DIR)/vigil
APP_BIN            := $(BUILD_DIR)/VigilMenuBar
SPARKLE_FRAMEWORK  := $(BUILD_DIR)/Sparkle.framework

APP_BUNDLE         := dist/$(APP_NAME).app
APP_CONTENTS       := $(APP_BUNDLE)/Contents
APP_MACOS          := $(APP_CONTENTS)/MacOS
APP_RESOURCES      := $(APP_CONTENTS)/Resources
APP_FRAMEWORKS     := $(APP_CONTENTS)/Frameworks

ENT_APP            := App/Vigil.entitlements
ENT_HELPER         := App/Helper.entitlements

# ---- Top-level targets ------------------------------------------------------

build:
	swift build -c release

icon:
	swift Scripts/make_app_icon.swift

# Bake the BUILD value into a Swift constant so the standalone privileged-helper
# binary (which has no Info.plist nearby) can report its own version for the
# menu-app's helper-version-mismatch handshake. Only runs for `make release`;
# `make app` keeps the checked-in default so the working tree stays clean.
_generate_version:
	@printf '// Generated by Makefile. Edits will be overwritten.\npublic enum VigilVersion {\n    public static let value = "%s"\n}\n' "$(BUILD)" > Sources/VigilIdentifiers/Version.swift

# Local ad-hoc dev build.
app: build icon _assemble _trim_sparkle _inject_version _inject_sparkle _sign_dev

# Release build for notarization. Sequenced via sub-makes so `_generate_version`
# regenerates Version.swift before `swift build` sees it (the bundled CLI bakes
# the version in for the menu-app's helper-version-mismatch handshake).
release: icon
	@if [ "$(CODESIGN_IDENTITY)" = "-" ]; then \
		echo "ERROR: release requires CODESIGN_IDENTITY=\"Developer ID Application: …\""; exit 1; \
	fi
	@if [ -z "$(SPARKLE_FEED_URL)" ] || [ -z "$(SPARKLE_PUBLIC_ED_KEY)" ]; then \
		echo "ERROR: release requires SPARKLE_FEED_URL and SPARKLE_PUBLIC_ED_KEY"; exit 1; \
	fi
	$(MAKE) _generate_version
	$(MAKE) build
	$(MAKE) _assemble _trim_sparkle _inject_version _inject_sparkle _sign_release verify

# ---- Internal helpers -------------------------------------------------------

_assemble:
	rm -rf "$(APP_BUNDLE)"
	install -d "$(APP_MACOS)" "$(APP_RESOURCES)" "$(APP_FRAMEWORKS)"
	install "App/Info.plist"   "$(APP_CONTENTS)/Info.plist"
	install "$(APP_BIN)"       "$(APP_MACOS)/$(APP_NAME)"
	install "$(CLI_BIN)"       "$(APP_RESOURCES)/vigil"
	install "App/AppIcon.icns" "$(APP_RESOURCES)/AppIcon.icns"
	ditto   "$(SPARKLE_FRAMEWORK)" "$(APP_FRAMEWORKS)/Sparkle.framework"
	install_name_tool -add_rpath "@executable_path/../Frameworks" \
		"$(APP_MACOS)/$(APP_NAME)" 2>/dev/null || true

# Sparkle 2 only needs the bundled XPC services when the host app is sandboxed.
# Vigil is intentionally non-sandboxed; remove them to shrink the signing surface.
# https://sparkle-project.org/documentation/sandboxing/
_trim_sparkle:
	rm -rf "$(APP_FRAMEWORKS)/Sparkle.framework/Versions/B/XPCServices"
	rm -f  "$(APP_FRAMEWORKS)/Sparkle.framework/XPCServices"

_inject_version:
	plutil -replace CFBundleIdentifier         -string  "$(BUNDLE_ID)" "$(APP_CONTENTS)/Info.plist"
	plutil -replace CFBundleShortVersionString -string  "$(VERSION)"   "$(APP_CONTENTS)/Info.plist"
	plutil -replace CFBundleVersion            -string  "$(BUILD)"     "$(APP_CONTENTS)/Info.plist"

_inject_sparkle:
	@if [ -n "$(SPARKLE_FEED_URL)" ] && [ -n "$(SPARKLE_PUBLIC_ED_KEY)" ]; then \
		plutil -replace SUFeedURL     -string "$(SPARKLE_FEED_URL)"      "$(APP_CONTENTS)/Info.plist" 2>/dev/null \
		  || plutil -insert SUFeedURL -string "$(SPARKLE_FEED_URL)"      "$(APP_CONTENTS)/Info.plist"; \
		plutil -replace SUPublicEDKey   -string "$(SPARKLE_PUBLIC_ED_KEY)" "$(APP_CONTENTS)/Info.plist" 2>/dev/null \
		  || plutil -insert SUPublicEDKey -string "$(SPARKLE_PUBLIC_ED_KEY)" "$(APP_CONTENTS)/Info.plist"; \
	fi

# Ad-hoc sign: single pass is fine for local dev. No hardened runtime, no timestamp.
_sign_dev:
	codesign --force --sign - "$(APP_BUNDLE)"

# Inside-out sign for release: nested Mach-Os first, then the framework,
# then the embedded CLI with its entitlements, then the outer app last.
# Each step requires --options runtime and --timestamp for notarization.
_sign_release:
	@set -e; \
	FLAGS="--force --options runtime --timestamp --sign \"$(CODESIGN_IDENTITY)\""; \
	eval codesign $$FLAGS \"$(APP_FRAMEWORKS)/Sparkle.framework/Versions/B/Updater.app\"; \
	eval codesign $$FLAGS \"$(APP_FRAMEWORKS)/Sparkle.framework/Versions/B/Autoupdate\"; \
	if [ -e "$(APP_FRAMEWORKS)/Sparkle.framework/Versions/B/Resources/fileop" ]; then \
		eval codesign $$FLAGS \"$(APP_FRAMEWORKS)/Sparkle.framework/Versions/B/Resources/fileop\"; \
	fi; \
	eval codesign $$FLAGS \"$(APP_FRAMEWORKS)/Sparkle.framework\"; \
	eval codesign $$FLAGS --entitlements "$(ENT_HELPER)" \"$(APP_RESOURCES)/vigil\"; \
	eval codesign $$FLAGS --entitlements "$(ENT_APP)"    \"$(APP_BUNDLE)\"

verify:
	codesign --verify --deep --strict --verbose=2 "$(APP_BUNDLE)"
	@if [ "$(CODESIGN_IDENTITY)" != "-" ]; then \
		spctl --assess --type execute --verbose=4 "$(APP_BUNDLE)" || true; \
	fi
	codesign -dvv "$(APP_BUNDLE)" 2>&1 | grep -E 'Authority|TeamIdentifier|Identifier'

install: build
	install -d "$(PREFIX)/bin"
	install "$(CLI_BIN)" "$(PREFIX)/bin/vigil"

uninstall:
	rm -f "$(PREFIX)/bin/vigil"

status: ; swift run vigil status
on:     ; swift run vigil on
off:    ; swift run vigil off
doctor: ; swift run vigil doctor

clean:
	rm -rf .build dist App/AppIcon.icns App/AppIcon.iconset
